# Generated by Django 5.0.6 on 2024-08-16 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Высота')),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Диаметр')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('application_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Метод нанесения')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Объём')),
                ('additional_details', models.TextField(blank=True, null=True, verbose_name='Дополнительные детали')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.productcategory', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Cувенир',
                'verbose_name_plural': 'Сувениры',
                'ordering': ('name',),
            },
        ),
    ]
