# Generated by Django 5.0.6 on 2024-08-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='description',
        ),
    ]
