# Generated by Django 5.0.6 on 2024-08-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_productcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Плотность'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='application_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Способ нанесения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Высота'),
        ),
    ]
