# Generated by Django 5.0.6 on 2024-08-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_density_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объём'),
        ),
    ]
