# Generated by Django 5.0.6 on 2024-08-19 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_color_product_parent_product_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_image_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent_product',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255, verbose_name='Цвет')),
                ('color_image', models.ImageField(blank=True, null=True, upload_to='variant_images/', verbose_name='Изображение цвета')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='variant_images/', verbose_name='Главное изображение')),
                ('additional_image_1', models.ImageField(blank=True, null=True, upload_to='variant_images/', verbose_name='Дополнительное изображение 1')),
                ('additional_image_2', models.ImageField(blank=True, null=True, upload_to='variant_images/', verbose_name='Дополнительное изображение 2')),
                ('additional_image_3', models.ImageField(blank=True, null=True, upload_to='variant_images/', verbose_name='Дополнительное изображение 3')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Сувенир')),
            ],
            options={
                'verbose_name': 'Вариант сувенира',
                'verbose_name_plural': 'Варианты сувенира',
            },
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
