# Generated by Django 5.0.6 on 2024-08-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Название'),
        ),
    ]
