# Generated by Django 5.0.6 on 2024-08-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_color_remove_productvariant_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color_image',
        ),
    ]
